# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(default='username', max_length=50)),
                ('title', models.CharField(default='Service', max_length=100)),
                ('description', models.TextField(default=models.CharField(default='Service', max_length=100))),
                ('location', models.CharField(default='U.S.', max_length=50)),
                ('final_time', models.CharField(default='0', max_length=20)),
                ('bid', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
