# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
