# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='client_username',
            field=models.CharField(default='username', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='final_time',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default='U.S.', max_length=50),
        ),
    ]
