# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_auto_20160401_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_username',
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_service_providers', to=settings.AUTH_USER_MODEL),
        ),
    ]
