# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20160402_0659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainUser',
        ),
    ]
