# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20160402_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], default='client', max_length=8),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(default='Your name', max_length=200),
        ),
    ]
