# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20160403_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='type',
            new_name='account_type',
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(default='Your name', max_length=40),
        ),
    ]
