# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20160403_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('can_review', 'can'),)},
        ),
    ]
