# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_service_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='closed',
        ),
    ]
