# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_remove_service_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_bid', to='market.Service'),
        ),
    ]
