# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20160408_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=models.CharField(default='Service', max_length=100)),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='Service', max_length=100),
        ),
    ]
