# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20160408_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='final_time',
            field=models.DateTimeField(default=datetime.date(2016, 4, 15), verbose_name='Ending Time'),
        ),
    ]
